name: Deploy Mobile App - Staging

on:
  push:
    branches: [staging]
    paths: ['mobile-app/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mobile-app/package-lock.json

      - name: Install dependencies
        working-directory: mobile-app
        run: npm ci

      - name: Run tests
        working-directory: mobile-app
        run: npm test || echo "No tests found"

      - name: Run linting
        working-directory: mobile-app
        run: npm run lint || echo "No lint script found"

      - name: Type check
        working-directory: mobile-app
        run: npx tsc --noEmit || echo "No TypeScript config found"

  build-staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mobile-app/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: mobile-app
        run: npm ci

      - name: Set Firebase project to staging
        working-directory: mobile-app
        run: |
          npx firebase use staging --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Copy staging environment
        working-directory: mobile-app
        run: |
          cp .env.staging .env
          # Override Mapbox token from secrets if available
          if [ -n "${{ secrets.MAPBOX_ACCESS_TOKEN_STAGING }}" ]; then
            sed -i.bak "s/pk.staging_mapbox_token_placeholder/${{ secrets.MAPBOX_ACCESS_TOKEN_STAGING }}/g" .env
          fi

      - name: Build staging app
        working-directory: mobile-app
        run: eas build --profile staging --platform all --non-interactive

      - name: Deploy Firebase Functions to staging
        working-directory: functions
        run: |
          npx firebase use staging --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy Firestore rules to staging
        run: |
          npx firebase use staging --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase deploy --only firestore:rules --token ${{ secrets.FIREBASE_TOKEN }}