name: Deploy Mobile App - Development

on:
  push:
    branches: [develop]
    paths: ['mobile-app/**']
  pull_request:
    branches: [develop]
    paths: ['mobile-app/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mobile-app/package-lock.json

      - name: Install dependencies
        working-directory: mobile-app
        run: npm ci

      - name: Run tests
        working-directory: mobile-app
        run: npm test || echo "No tests found"

      - name: Run linting
        working-directory: mobile-app
        run: npm run lint || echo "No lint script found"

      - name: Type check
        working-directory: mobile-app
        run: npx tsc --noEmit || echo "No TypeScript config found"

  build-development:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mobile-app/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: mobile-app
        run: npm ci

      - name: Set Firebase project to development
        working-directory: mobile-app
        run: |
          npx firebase use development --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Copy development environment
        working-directory: mobile-app
        run: |
          cp .env.development .env
          # Override Mapbox token from secrets if available
          if [ -n "${{ secrets.MAPBOX_ACCESS_TOKEN_DEV }}" ]; then
            sed -i.bak "s/pk.development_mapbox_token_placeholder/${{ secrets.MAPBOX_ACCESS_TOKEN_DEV }}/g" .env
          fi

      - name: Build development app
        working-directory: mobile-app
        run: eas build --profile development --platform all --non-interactive

      - name: Comment PR with build link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Development build triggered! Check EAS dashboard for progress.'
            })